baseURL: http://evandibona.com
params:
  AuthorName: Evan DiBona
languageCode: en-us
title: Evan
disableKinds:
  - taxonomy
  - term
markup:
  goldmark:
    extensions:
    renderer:
      unsafe: true
    
security:
  exec:
    allow:
    - ^vim
    osEnv:
    - .*
